### ISSUE TITLE
BasePlayer should be able to play the bases

### ISSUE THREAD

**Issue by gringer** [rkataine/BasePlayer#1]
In my discussions with other people about turning DNA into sound, one person suggested translating the DNA sequence into a jazz scale, so that every sequence sounds good regardless of what it is. That sounded like a pretty good idea, but I've never got around to implementing that.

Examples of my attempts at direct conversion (creating discordant notes) are here:

https://soundcloud.com/david-eccles-513326868

**Comment by esaskar** [comment]
Thanks @gringer - that's interesting! 23andme encoded variants into music by [mapping genotypes to musical parameters](https://blog.23andme.com/23andme-and-you/dna-melody-play-it-again/) (rhythm, pitch, timbre, and key signature). Since BasePlayer's focus is on variant analysis, something like this could be appropriate.
